POST http://localhost:3000/test
Content-Type: application/json

{
    "test" : "test"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email"    : "dangtung006@gmail.com",
    "password" : "343434"
}

###
GET http://localhost:3000/person?email=minhhieu006@gmail.com&password=123456

###
GET http://localhost:3000/person?nation=usa&name=John&height=170&weight=60

###
GET http://localhost:3000/user/us/10

###
GET http://localhost:3000/product/list

###
GET http://localhost:3000/product/search?k=bao_hanh&&v=24

###
GET http://localhost:3000/product/delete?id=63aafa10523f0137026513fc

###
POST http://localhost:3000/product/create
Content-Type: application/json

{
    "name"          : "Camera Ezviz C1C",
    "brand"         : "EZVIZ",
    "code"          : "C1C",
    "description"   : "Wifi Trong Nhà Góc Siêu Rộng, Bảo Hành Chính Hãng 24 Tháng",

    "specs"         : [
        { "k" : "do_phan_giai" , "v" : 1080, "u" : "p"},
        { "k" : "loai_the_nho",  "v" : "Micro SD" },
        { "k" : "bao_hanh" ,     "v" : 24, "u" : "m"}
    ]
}

###
POST http://localhost:3000/product/edit
Content-Type: application/json

{
    "id"            : "63aafc8c7350d32445005a69",
    "name"          : "Camera Ezviz C1C0",
    "brand"         : "EZVIZ",
    "code"          : "C1C0",
    "description"   : "Wifi Trong Nhà Góc Siêu Rộng",

    "specs"         : [
        { "k" : "do_phan_giai" , "v" : 1080, "u" : "p"},
        { "k" : "loai_the_nho",  "v" : "Micro SD" },
        { "k" : "bao_hanh" ,     "v" : 12, "u" : "m"}
    ]
}

###
GET http://localhost:3000/client/detail?id=63ac3e2e905f2b8e6fe21e36

###
POST http://localhost:3000/client/create
Content-Type: application/json

{
    "name"            : "Nguyen Van A",
    "address"         : "Hanoi",
    "dateOfBirth"     : "2002-12-09"
}

###
POST http://localhost:3000/client/save/payment_method
Content-Type: application/json

{
    "id"            : "63ac3e2e905f2b8e6fe21e36",
    "clientName"    : "Nguyen Van A",
    "phone"         : "0915330567",
    "cardId"        : "0xxxxx12424",
    "qr"            : "",
    "note"          : "Wifi Trong Nhà Góc Siêu Rộng",
    "type"          : 1
}
