module.exports = {
    SUCCESS: "SUCCESS",
    BAD_REQUEST: "BAD_REQUEST",
    SERVER_ERROR: "SERVER_ERROR",
    INVALID_INPUT: "INVALID_INPUT",
    INVALID_SIGN: "INVALID_SIGN",
    END_ROUND_FINISH: "END_ROUND_FINISH",
    CURRENT_ROUND_NOT_FOUND: "CURRENT_ROUND_NOT_FOUND",
}